import Foundation

/// Currency glyphs available for the configurable Lock Screen icon.
public enum CurrencySymbol: String, CaseIterable, Identifiable, Sendable {
  case austral = "australsign"
  case australiandollar = "australiandollarsign"
  case baht = "bahtsign"
  case bitcoin = "bitcoinsign"
  case brazilianreal = "brazilianrealsign"
  case cedi = "cedisign"
  case cent = "centsign"
  case chineseyuanrenminbi = "chineseyuanrenminbisign"
  case coloncurrency = "coloncurrencysign"
  case cruzeiro = "cruzeirosign"
  case danishkrone = "danishkronesign"
  case dong = "dongsign"
  case dollar = "dollarsign"
  case euro = "eurosign"
  case eurozone = "eurozonesign"
  case florin = "florinsign"
  case franc = "francsign"
  case guarani = "guaranisign"
  case hryvnia = "hryvniasign"
  case indianrupee = "indianrupeesign"
  case kip = "kipsign"
  case lari = "larisign"
  case lira = "lirasign"
  case malaysianringgit = "malaysianringgitsign"
  case manat = "manatsign"
  case mill = "millsign"
  case naira = "nairasign"
  case norwegiankrone = "norwegiankronesign"
  case peruviansoles = "peruviansolessign"
  case peseta = "pesetasign"
  case peso = "pesosign"
  case polishzloty = "polishzlotysign"
  case ruble = "rublesign"
  case rupee = "rupeesign"
  case shekel = "shekelsign"
  case singaporedollar = "singaporedollarsign"
  case sterling = "sterlingsign"
  case swedishkrona = "swedishkronasign"
  case tenge = "tengesign"
  case tugrik = "tugriksign"
  case turkishlira = "turkishlirasign"
  case won = "wonsign"
  case yen = "yensign"
  /// SF Symbols name and stable configuration identity.
  public var id: String { rawValue }
}
