import Foundation

/// Currency glyphs available for the configurable Lock Screen icon.
public enum CurrencySymbol: String, CaseIterable, Identifiable, Sendable {
  case austral = "australsign"
  case australiandollar = "australiandollarsign"
  case baht = "bahtsign"
  case bitcoin = "bitcoinsign"
  case brazilianreal = "brazilianrealsign"
  case cedi = "cedisign"
  case cent = "centsign"
  case chineseyuanrenminbi = "chineseyuanrenminbisign"
  case coloncurrency = "coloncurrencysign"
  case cruzeiro = "cruzeirosign"
  case danishkrone = "danishkronesign"
  case dong = "dongsign"
  case dollar = "dollarsign"
  case euro = "eurosign"
  case eurozone = "eurozonesign"
  case florin = "florinsign"
  case franc = "francsign"
  case guarani = "guaranisign"
  case hryvnia = "hryvniasign"
  case indianrupee = "indianrupeesign"
  case kip = "kipsign"
  case lari = "larisign"
  case lira = "lirasign"
  case malaysianringgit = "malaysianringgitsign"
  case manat = "manatsign"
  case mill = "millsign"
  case naira = "nairasign"
  case norwegiankrone = "norwegiankronesign"
  case peruviansoles = "peruviansolessign"
  case peseta = "pesetasign"
  case peso = "pesosign"
  case polishzloty = "polishzlotysign"
  case ruble = "rublesign"
  case rupee = "rupeesign"
  case shekel = "shekelsign"
  case singaporedollar = "singaporedollarsign"
  case sterling = "sterlingsign"
  case swedishkrona = "swedishkronasign"
  case tenge = "tengesign"
  case tugrik = "tugriksign"
  case turkishlira = "turkishlirasign"
  case won = "wonsign"
  case yen = "yensign"
  /// SF Symbols name and stable configuration identity.
  public var id: String { rawValue }
  /// Human-readable name for pickers and accessibility.
  public var title: String {
    switch self {
    case .austral: "Austral"
    case .australiandollar: "Australian dollar"
    case .baht: "Thai baht"
    case .bitcoin: "Bitcoin"
    case .brazilianreal: "Brazilian real"
    case .cedi: "Ghanaian cedi"
    case .cent: "Cent"
    case .chineseyuanrenminbi: "Chinese yuan"
    case .coloncurrency: "Colón"
    case .cruzeiro: "Cruzeiro"
    case .danishkrone: "Danish krone"
    case .dong: "Vietnamese dong"
    case .dollar: "Dollar"
    case .euro: "Euro"
    case .eurozone: "Eurozone"
    case .florin: "Florin"
    case .franc: "Franc"
    case .guarani: "Guaraní"
    case .hryvnia: "Ukrainian hryvnia"
    case .indianrupee: "Indian rupee"
    case .kip: "Lao kip"
    case .lari: "Georgian lari"
    case .lira: "Lira"
    case .malaysianringgit: "Malaysian ringgit"
    case .manat: "Manat"
    case .mill: "Mill"
    case .naira: "Nigerian naira"
    case .norwegiankrone: "Norwegian krone"
    case .peruviansoles: "Peruvian sol"
    case .peseta: "Peseta"
    case .peso: "Peso"
    case .polishzloty: "Polish złoty"
    case .ruble: "Ruble"
    case .rupee: "Rupee"
    case .shekel: "Shekel"
    case .singaporedollar: "Singapore dollar"
    case .sterling: "Pound sterling"
    case .swedishkrona: "Swedish krona"
    case .tenge: "Kazakh tenge"
    case .tugrik: "Mongolian tugrik"
    case .turkishlira: "Turkish lira"
    case .won: "Korean won"
    case .yen: "Yen"
    }
  }
}
